### ISSUE TITLE
Contributing to rsip

### ISSUE THREAD

**Issue by yugely** [vasilakisfil/rsip#22]
I am moving over here from the SIP server.  I was reading over the locating sip server literature with RFC 3263. After reading through your code, you are doing a lot of nuanced things that I don't fully understand the reason for and I realized I'm not comfortable enough with Rust to contribute to the issue that was initially brought up.
I would definitely take some real easy issue if there is one. Otherwise, I am putting this on the backburner while I start the Rust portion of another personal project I'm doing. It was really cool looking through the code and see what someone who really knows their stuff is doing with the language.

Apologies if this is the wrong forum for this, I just didn't want to say I will contribute and then disappear.

**Comment by vasilakisfil** [comment]
Yeah no worries, makes sense if you just getting started with Rust, even when I look in other crates like Serde, Diesel etc I also don't understand match and I am working professionally with Rust 2+ years :P
