### ISSUE TITLE
example parsing header?

### ISSUE THREAD

**Issue by horacimacias** [vasilakisfil/rsip#46]
I'm trying to use this crate to parse SIP headers but I'm having a bit of a hard time finding how to actually go from a String or &str into a header, for example From, To.
Is there some code I can look at in order to do this?

**Comment by ghost** [comment]
I am not sure if it's the best way but the way I do it is like this 

```rust
    let message = String::from_utf8_lossy(&slice);  // this converts Vec<u8> into a string
    SipMessage::try_from(message.to_string()) // this gives you a Result<SipMessage, rsip::Error>
```

**Comment by horacimacias** [comment]
thanks, I'll give this a try. 
I was actually looking at parsing specific headers (e.g. parsing a String that I know represents a From), but I may end up parsing the whole message instead.

**Comment by elasticrash** [comment]
I am quite certain you can do the same thing with individual typed headers as well. I think try_from is implemented for &str for most
